package Screen;


import Control.AdmCelebrities;
import Control.AdmFollowers;
import Model.Celebrity;
import Model.Follower;
import Model.Post;
import Socket.Settings;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Esteb
 */
public class FrFollower extends javax.swing.JFrame {

    /**
     * Creates new form FrFollower
     */
    Follower oneFollower; 
    private DefaultListModel notificationsList;
    Post currenPost;
    public FrFollower() {
        initComponents();
        Settings.getInstance().setPORT(60000);
        String name = JOptionPane.showInputDialog("Ingrese su nombre de usuario: ");
        oneFollower = new Follower(name);
        AdmFollowers.getInstance().addFollowers(oneFollower);
        jLabelName.setText(name);
        notificationsList = new DefaultListModel();
        oneFollower.setSscreen(this);
        
    }
    public void addNotification(Post newPost){
        notificationsList.addElement(newPost.getTitle());
        this.jListNotificaciones.setModel(notificationsList);
    }
    public void fillComboBoxCelebrity(){
        for(Celebrity oneCelebrity: AdmCelebrities.getInstance().getListaCelebridades()){
            this.jComboBoxCelebrities.addItem(oneCelebrity.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelNotificaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNotificaciones = new javax.swing.JList<>();
        jButtonNext = new javax.swing.JButton();
        jButtonLike = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPost = new javax.swing.JTextArea();
        jButtonDislike = new javax.swing.JButton();
        jLabelLikes = new javax.swing.JLabel();
        jLabelDislikes = new javax.swing.JLabel();
        jButtonSuscribirse = new javax.swing.JButton();
        jComboBoxCelebrities = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setText("jLabel1");

        jLabelNotificaciones.setText("Notificaciones");

        jScrollPane1.setViewportView(jListNotificaciones);

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonLike.setText("Like");
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });

        jTextAreaPost.setColumns(20);
        jTextAreaPost.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPost);

        jButtonDislike.setText("Dislike");
        jButtonDislike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDislikeActionPerformed(evt);
            }
        });

        jButtonSuscribirse.setText("Follow");
        jButtonSuscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuscribirseActionPerformed(evt);
            }
        });

        jComboBoxCelebrities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCelebritiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNotificaciones)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonLike)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDislike)
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtonNext, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(198, 198, 198)
                                .addComponent(jLabelDislikes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonSuscribirse)
                            .addComponent(jComboBoxCelebrities, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNotificaciones)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDislike))
                    .addComponent(jButtonLike, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLikes)
                    .addComponent(jLabelDislikes))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCelebrities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonSuscribirse)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
       currenPost = this.oneFollower.nextPost();
       this.jButtonLike.setEnabled(true);
       this.jButtonDislike.setEnabled(false);
       this.jTextAreaPost.setText(currenPost.getTitle()+"\n"+currenPost.getMessage());
       this.jLabelLikes.setText(String.valueOf(currenPost.getLikes()));
       this.jLabelDislikes.setText(String.valueOf(currenPost.getDislikes()));
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed
        this.jButtonLike.setEnabled(false);
        this.jButtonDislike.setEnabled(true);
        this.currenPost.incrementLikes();
        this.jLabelLikes.setText(String.valueOf(currenPost.getLikes()));
        this.jLabelDislikes.setText(String.valueOf(currenPost.getDislikes()));
    }//GEN-LAST:event_jButtonLikeActionPerformed

    private void jButtonDislikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDislikeActionPerformed
        this.jButtonDislike.setEnabled(false);
        this.jButtonLike.setEnabled(true);
        this.currenPost.incrementeDislikes();
        this.jLabelLikes.setText(String.valueOf(currenPost.getLikes()));
        this.jLabelDislikes.setText(String.valueOf(currenPost.getDislikes()));
    }//GEN-LAST:event_jButtonDislikeActionPerformed

    private void jComboBoxCelebritiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCelebritiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCelebritiesActionPerformed

    private void jButtonSuscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuscribirseActionPerformed
        int index = this.jComboBoxCelebrities.getSelectedIndex();
        Celebrity oneCelebrity = AdmCelebrities.getInstance().getListaCelebridades().get(index);
        if(oneFollower.searchCelebrity(oneCelebrity) == null){
            oneFollower.addCelebrity(oneCelebrity);
            System.out.println("Celebrity added");
            JOptionPane.showMessageDialog(null, "Celebrity added");
        }
    }//GEN-LAST:event_jButtonSuscribirseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrFollower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrFollower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrFollower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrFollower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrFollower().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDislike;
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonSuscribirse;
    private javax.swing.JComboBox<String> jComboBoxCelebrities;
    private javax.swing.JLabel jLabelDislikes;
    private javax.swing.JLabel jLabelLikes;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNotificaciones;
    private javax.swing.JList<String> jListNotificaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaPost;
    // End of variables declaration//GEN-END:variables

    public DefaultListModel getNotificationsList() {
        return notificationsList;
    }
}
